In [206]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df_books = pd.read_csv("../Downloads/archive (2)/Books.csv")

C:\Users\91962\AppData\Local\Temp\ipykernel_15780\213035809.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_books = pd.read_csv("../Downloads/archive (2)/Books.csv")

In [3]:
df_books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [4]:
df_users = pd.read_csv("../Downloads/archive (2)/Users.csv")

In [5]:
df_ratings = pd.read_csv("../Downloads/archive (2)/Ratings.csv")

In [6]:
df_ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [7]:
df_books.shape

(271360, 8)

In [8]:
df_ratings.shape

(1149780, 3)

In [9]:
len(df_users)

278858

In [10]:
df_ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [11]:
df_books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [12]:
df_users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [13]:
df_users.duplicated().sum()

0

# popularity based recommendation system

In [14]:
final_df = pd.merge(df_books,df_ratings, on='ISBN', how='left')

In [15]:
final_df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2.0,0.0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8.0,5.0
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11400.0,0.0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676.0,8.0
4,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,41385.0,0.0
...,...,...,...,...,...,...,...,...,...,...
1032340,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,276463.0,7.0
1032341,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,276579.0,4.0
1032342,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,276680.0,0.0
1032343,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,276680.0,0.0
1032344,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,276680.0,0.0

In [16]:
final_df.shape

(1032345, 10)

In [17]:
final_df.isnull().sum()

ISBN                      0
Book-Title                0
Book-Author               1
Year-Of-Publication       0
Publisher                 2
Image-URL-S               0
Image-URL-M               0
Image-URL-L               4
User-ID                1209
Book-Rating            1209
dtype: int64

In [20]:
final_df.drop(['User-ID','Image-URL-S','Image-URL-M','Image-URL-L','Publisher'],axis=1, inplace=True)

In [21]:
final_df

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,0.0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,5.0
2,0002005018,Clara Callan,Richard Bruce Wright,2001,0.0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,8.0
4,0002005018,Clara Callan,Richard Bruce Wright,2001,0.0
...,...,...,...,...,...
1032340,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,7.0
1032341,0525447644,From One to One Hundred,Teri Sloat,1991,4.0
1032342,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,0.0
1032343,0192126040,Republic (World's Classics),Plato,1996,0.0
1032344,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,0.0

In [22]:
book_count = final_df.groupby(['Book-Title'])['Book-Rating'].count().reset_index().rename(columns={'Book-Rating':'Rating-count'})

In [23]:
book_count

                                               Book-Title  Rating-count
0        A Light in the Storm: The Civil War Diary of ...             4
1                                   Always Have Popsicles             1
2                    Apple Magic (The Collector's series)             1
3        Ask Lily (Young Women of Faith: Lily Series, ...             1
4        Beyond IBM: Leadership Marketing and Finance ...             1
...                                                   ...           ...
242130                                      Ãƒ?Ã‚?lpiraten.             2
242131                     Ãƒ?Ã‚?rger mit Produkt X. Roman.             4
242132                                Ãƒ?Ã‚?sterlich leben.             1
242133                              Ãƒ?Ã‚?stlich der Berge.             3
242134                                  Ãƒ?Ã‚?thique en toc             2

[242135 rows x 2 columns]

In [24]:
avg_rating = final_df.groupby(['Book-Title'])['Book-Rating'].mean().reset_index().rename(columns={'Book-Rating':'Avg-Rating'})

In [25]:
avg_rating

                                               Book-Title  Avg-Rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
242130                                      Ãƒ?Ã‚?lpiraten.    0.000000
242131                     Ãƒ?Ã‚?rger mit Produkt X. Roman.    5.250000
242132                                Ãƒ?Ã‚?sterlich leben.    7.000000
242133                              Ãƒ?Ã‚?stlich der Berge.    2.666667
242134                                  Ãƒ?Ã‚?thique en toc    4.000000

[242135 rows x 2 columns]

In [26]:
df = pd.merge(book_count,avg_rating, on='Book-Title')

In [27]:
df

,Book-Title,Rating-count,Avg-Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
242130,Ãƒ?Ã‚?lpiraten.,2,0.000000
242131,Ãƒ?Ã‚?rger mit Produkt X. Roman.,4,5.250000
242132,Ãƒ?Ã‚?sterlich leben.,1,7.000000
242133,Ãƒ?Ã‚?stlich der Berge.,3,2.666667
242134,Ãƒ?Ã‚?thique en toc,2,4.000000

In [28]:
df = df[df['Rating-count'] >=250].sort_values(by='Avg-Rating', ascending=False).reset_index()

In [31]:
df

,index,Book-Title,Rating-count,Avg-Rating
0,80812,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
1,80800,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
2,80819,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
3,80804,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
4,80792,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
...,...,...,...,...
181,228700,Vinegar Hill (Oprah's Book Club (Paperback)),265,2.245283
182,234667,Whispers,286,2.199301
183,144043,Presumed Innocent,294,2.139456
184,94816,Isle of Dogs,288,2.000000
185,235991,Wild Animus,2502,1.019584

# Collaborative filtering based recommender system

In [86]:
cf = df_ratings.groupby('User-ID')['Book-Rating'].count() > 200

In [94]:
padhe_likhe = cf[cf].index

In [45]:
final_cf = pd.merge(df_books,df_ratings, on='ISBN', how='left')

In [97]:
filtered_rating = final_cf[final_cf['User-ID'].isin(padhe_likhe)]

In [114]:
bf = bf[filtered_rating.groupby('Book-Title')['Book-Rating'].count() >= 50]

In [118]:
bf.index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=742)

In [119]:
final_rating = filtered_rating[filtered_rating['Book-Title'].isin(bf.index)]

In [122]:
final_rating.duplicated().sum()

0

In [128]:
pt = final_rating.pivot_table(index = 'Book-Title', columns='User-ID', values= 'Book-Rating')

In [130]:
pt = pt.fillna(0)

In [131]:
pt

User-ID,254.0,2276.0,2766.0,2977.0,3363.0,3757.0,4017.0,4385.0,6242.0,6251.0,...,274004.0,274061.0,274301.0,274308.0,274808.0,275970.0,277427.0,277478.0,277639.0,278418.0
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# USING COSINE SIMILARITY

In [132]:
from sklearn.metrics.pairwise import cosine_similarity

In [137]:
similarity_score = cosine_similarity(pt)

In [139]:
similarity_score[0]

array([1.        , 0.09259251, 0.01122267, 0.        , 0.08708674,
       0.04847394, 0.02550819, 0.0730769 , 0.11207963, 0.        ,
       0.01285476, 0.02998295, 0.03371421, 0.02134876, 0.06139476,
       0.01868845, 0.0825378 , 0.1230767 , 0.06731328, 0.10252858,
       0.04630962, 0.02314465, 0.10542489, 0.        , 0.12738003,
       0.0711696 , 0.05634353, 0.07792927, 0.        , 0.06328801,
       0.12354715, 0.06986576, 0.11043489, 0.03201052, 0.05842928,
       0.01354254, 0.        , 0.07322549, 0.04157401, 0.02792663,
       0.01419341, 0.11367471, 0.0872911 , 0.01630857, 0.02242419,
       0.07048157, 0.10736773, 0.        , 0.04839326, 0.07380827,
       0.07787765, 0.07906263, 0.0497226 , 0.05042114, 0.28393467,
       0.08989427, 0.09244761, 0.1152654 , 0.10803669, 0.0697622 ,
       0.04006742, 0.01765755, 0.        , 0.05028458, 0.00501224,
       0.07003198, 0.04718206, 0.1738128 , 0.        , 0.01140469,
       0.02743558, 0.03767901, 0.11453863, 0.14358757, 0.        ,
       0.07197121, 0.12011177, 0.06081257, 0.        , 0.        ,
       0.        , 0.09810262, 0.02579964, 0.04004899, 0.02297666,
       0.06320861, 0.0740467 , 0.09669683, 0.02988232, 0.01181591,
       0.21757995, 0.        , 0.09558273, 0.05669687, 0.13031493,
       0.10348915, 0.07658256, 0.00782183, 0.05548817, 0.        ,
       0.13275059, 0.03015608, 0.00982597, 0.02268375, 0.01944077,
       0.02470732, 0.01938536, 0.        , 0.01472323, 0.11135999,
       0.04346962, 0.05349266, 0.05682825, 0.        , 0.04382095,
       0.04661655, 0.02407479, 0.05997693, 0.01909076, 0.01860772,
       0.06768198, 0.01611235, 0.03089472, 0.        , 0.01383233,
       0.10147977, 0.15192645, 0.14261487, 0.05333933, 0.07285264,
       0.05049889, 0.06632302, 0.03467296, 0.05456952, 0.02657103,
       0.02814174, 0.04263373, 0.00925353, 0.01497405, 0.06672752,
       0.        , 0.        , 0.        , 0.02232392, 0.02820083,
       0.09169468, 0.        , 0.        , 0.01553667, 0.02216177,
       0.02583855, 0.        , 0.        , 0.01666481, 0.02581471,
       0.        , 0.10731452, 0.01955855, 0.14050262, 0.02543324,
       0.0907663 , 0.09099368, 0.13002916, 0.04603063, 0.08025483,
       0.01276075, 0.        , 0.07071673, 0.00810998, 0.04151225,
       0.        , 0.01157232, 0.03680051, 0.065663  , 0.01119556,
       0.01672677, 0.02452076, 0.01317156, 0.1324213 , 0.05595714,
       0.02370113, 0.0252046 , 0.        , 0.13152387, 0.05154022,
       0.        , 0.06494685, 0.02941513, 0.03349567, 0.        ,
       0.01804409, 0.19861983, 0.01393435, 0.0889212 , 0.01779363,
       0.01790853, 0.04964237, 0.06675586, 0.01021868, 0.03355133,
       0.05510575, 0.03768632, 0.13057503, 0.01827179, 0.09523061,
       0.08825721, 0.06076218, 0.11418037, 0.08266546, 0.01054796,
       0.02261499, 0.        , 0.16591675, 0.04572788, 0.03992728,
       0.09973548, 0.11916537, 0.05304176, 0.04939098, 0.03175053,
       0.        , 0.08459863, 0.05872517, 0.04027288, 0.13986986,
       0.07543217, 0.1126297 , 0.07840756, 0.07278759, 0.11194157,
       0.02237173, 0.00250828, 0.        , 0.        , 0.03310451,
       0.13750173, 0.03409882, 0.06760556, 0.08865823, 0.04978724,
       0.11499688, 0.06858337, 0.05907563, 0.03278828, 0.01433797,
       0.01869342, 0.0226465 , 0.        , 0.10568011, 0.0191643 ,
       0.01749666, 0.06256637, 0.01748144, 0.10833052, 0.06766928,
       0.07703866, 0.        , 0.01875995, 0.        , 0.09078976,
       0.07624704, 0.12748336, 0.0105352 , 0.121974  , 0.06824018,
       0.10625431, 0.04406979, 0.01490713, 0.02420398, 0.04427066,
       0.01801563, 0.08909518, 0.11900247, 0.        , 0.05065298,
       0.02631529, 0.01671836, 0.        , 0.07628905, 0.03201239,
       0.15062886, 0.07509215, 0.06246606, 0.02746391, 0.        ,
       0.        , 0.11857887, 0.07248517, 0.04411519, 0.01302091,
       0.0195233 , 0.04182502, 0.07973517, 0.00814451, 0.02648016,
       0.0185885 , 0.02219174, 0.11393263, 0.        , 0.02282047,
       0.05994046, 0.        , 0.05579672, 0.07935122, 0.12687792,
       0.01708614, 0.01087683, 0.07913428, 0.        , 0.039796  ,
       0.02527453, 0.01781743, 0.0601359 , 0.07231593, 0.12745366,
       0.10807488, 0.01671546, 0.12210306, 0.04420968, 0.08925362,
       0.        , 0.22183479, 0.06665784, 0.        , 0.10937992,
       0.09701579, 0.00958215, 0.02372437, 0.        , 0.08228536,
       0.0368209 , 0.17208283, 0.02084403, 0.01590616, 0.0280742 ,
       0.06210013, 0.12954445, 0.09622321, 0.01547517, 0.10998998,
       0.09264529, 0.03210555, 0.02452076, 0.07034779, 0.11002631,
       0.01596282, 0.01367684, 0.01977438, 0.14058373, 0.        ,
       0.        , 0.00903116, 0.0197922 , 0.02708508, 0.        ,
       0.01803908, 0.01067101, 0.00876662, 0.17802357, 0.01385445,
       0.03587507, 0.08533452, 0.10135372, 0.08286985, 0.05437101,
       0.05705633, 0.        , 0.0180732 , 0.07210172, 0.14061524,
       0.06331105, 0.        , 0.13416643, 0.06456252, 0.02702345,
       0.04393659, 0.01661298, 0.10116113, 0.09000596, 0.07353691,
       0.07929489, 0.10058193, 0.        , 0.01944981, 0.05051374,
       0.01652028, 0.0529064 , 0.01940558, 0.08645551, 0.11333464,
       0.        , 0.06278367, 0.08055866, 0.        , 0.02556799,
       0.01382455, 0.0911898 , 0.0161538 , 0.02271729, 0.01656097,
       0.10558832, 0.0594582 , 0.12781382, 0.        , 0.0573265 ,
       0.        , 0.        , 0.05296779, 0.04341328, 0.02083102,
       0.0077665 , 0.02062403, 0.02111952, 0.06559999, 0.        ,
       0.13871356, 0.05374402, 0.        , 0.08270382, 0.01421106,
       0.09316841, 0.        , 0.01540974, 0.        , 0.04336209,
       0.14745804, 0.        , 0.12085303, 0.11323603, 0.02140958,
       0.01826792, 0.01016387, 0.02342272, 0.00811441, 0.07342598,
       0.01698246, 0.06457711, 0.01988946, 0.11787484, 0.09023158,
       0.07944953, 0.0551338 , 0.0265021 , 0.03985694, 0.01812582,
       0.04256798, 0.04801899, 0.        , 0.08257364, 0.00804924,
       0.09122183, 0.0925734 , 0.        , 0.11313622, 0.0161689 ,
       0.01864347, 0.09270623, 0.11976104, 0.03542741, 0.08143258,
       0.08277818, 0.04901469, 0.22032229, 0.07384709, 0.04050211,
       0.05644072, 0.02026571, 0.02088506, 0.0593847 , 0.01760691,
       0.        , 0.04175923, 0.        , 0.        , 0.04768094,
       0.01210729, 0.        , 0.        , 0.04466905, 0.067548  ,
       0.09518323, 0.01580007, 0.0911887 , 0.07358213, 0.00323483,
       0.02048857, 0.04372978, 0.10224565, 0.04728128, 0.04979885,
       0.        , 0.05596116, 0.05842451, 0.0992843 , 0.        ,
       0.0694462 , 0.        , 0.12542555, 0.04409408, 0.14803611,
       0.11062924, 0.        , 0.01617749, 0.04999135, 0.        ,
       0.        , 0.07249541, 0.12033593, 0.00534858, 0.064098  ,
       0.04990119, 0.0543672 , 0.10478866, 0.04572986, 0.17729108,
       0.10328163, 0.05932259, 0.05884982, 0.        , 0.        ,
       0.09654368, 0.10479805, 0.04063622, 0.0167788 , 0.        ,
       0.01098685, 0.23041012, 0.05102653, 0.03911561, 0.0233896 ,
       0.0668881 , 0.04744589, 0.06657337, 0.09930446, 0.01475473,
       0.02235433, 0.01924502, 0.12517436, 0.10638001, 0.07173002,
       0.        , 0.08420138, 0.09964696, 0.0631429 , 0.07538694,
       0.1171271 , 0.        , 0.17272734, 0.02101588, 0.07153391,
       0.        , 0.09508544, 0.06193936, 0.        , 0.17763427,
       0.05701022, 0.03216795, 0.01657254, 0.09073845, 0.08821511,
       0.02004113, 0.02130369, 0.02376353, 0.05953179, 0.0626006 ,
       0.11503765, 0.1563521 , 0.06558483, 0.01046994, 0.07851486,
       0.16185691, 0.07132022, 0.02122493, 0.01599144, 0.15377874,
       0.24264615, 0.16922331, 0.05148033, 0.03799785, 0.06352928,
       0.1328941 , 0.19708288, 0.17657715, 0.01989949, 0.18407974,
       0.01385905, 0.04623765, 0.11337695, 0.12938351, 0.02004113,
       0.07547949, 0.02172572, 0.11627236, 0.00917965, 0.06166394,
       0.08366537, 0.12226825, 0.03145566, 0.06613256, 0.05976008,
       0.02111582, 0.14104995, 0.07984611, 0.        , 0.        ,
       0.01726948, 0.08740164, 0.03914057, 0.13654317, 0.01399323,
       0.09077603, 0.05146847, 0.04075879, 0.0833307 , 0.05954915,
       0.1307467 , 0.07604448, 0.        , 0.03864239, 0.02025752,
       0.1597819 , 0.01755731, 0.14479175, 0.12902649, 0.        ,
       0.05460828, 0.07101287, 0.06742509, 0.06018029, 0.06341948,
       0.17136758, 0.02292726, 0.01487592, 0.04998517, 0.04373857,
       0.        , 0.10271913, 0.0735544 , 0.11338575, 0.02120388,
       0.0563416 , 0.01921932, 0.0418337 , 0.09370759, 0.        ,
       0.09859824, 0.0239495 , 0.00159681, 0.09075668, 0.10499526,
       0.05713654, 0.01483917, 0.01889496, 0.09006289, 0.0168029 ,
       0.17071974, 0.04912985, 0.17397033, 0.05418214, 0.0581792 ,
       0.1105374 , 0.07677389, 0.08739526, 0.00963486, 0.08963071,
       0.06869203, 0.0730293 , 0.        , 0.21271076, 0.00986941,
       0.11841834, 0.04208819, 0.13273939, 0.        , 0.11511685,
       0.05933747, 0.02589998, 0.12911579, 0.01582065, 0.08740346,
       0.04760797, 0.16637395, 0.1390345 , 0.09631288, 0.12102994,
       0.03635496, 0.03157109, 0.02264556, 0.        , 0.06939828,
       0.03062774, 0.02764801, 0.02283479, 0.03882599, 0.13278075,
       0.10729076, 0.01388247, 0.02614678, 0.01898932, 0.06794868,
       0.08185226, 0.14610389, 0.06386534, 0.10156082, 0.00975125,
       0.        , 0.08367943, 0.05250146, 0.08722157, 0.00872313,
       0.12286538, 0.05326174, 0.        , 0.06178518, 0.01900081,
       0.        , 0.01690888, 0.        , 0.11608616, 0.07432008,
       0.0820779 , 0.00671591, 0.07486236, 0.        , 0.03868444,
       0.07715099, 0.07157072, 0.        , 0.06471902, 0.02213172,
       0.01429081, 0.032511  , 0.04591602, 0.00995685, 0.00890497,
       0.11130285, 0.06172108, 0.05204756, 0.0162674 , 0.11132415,
       0.06754227, 0.03967511])

In [174]:
def recommend(book_name):
    index = np.where(pt.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])), key=lambda x: x[1], reverse=True)[1:6]
    for i in similar_items:
        yield pt.index[i[0]]

In [143]:
pt

User-ID,254.0,2276.0,2766.0,2977.0,3363.0,3757.0,4017.0,4385.0,6242.0,6251.0,...,274004.0,274061.0,274301.0,274308.0,274808.0,275970.0,277427.0,277478.0,277639.0,278418.0
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [241]:
for i in recommend('Harry Potter and the Prisoner of Azkaban (Book 3)'):
    print(i)

Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Chamber of Secrets (Book 2)
Harry Potter and the Order of the Phoenix (Book 5)
Harry Potter and the Sorcerer's Stone (Book 1)
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))

# Using Nearest Neighbors

In [178]:
from scipy.sparse import csr_matrix

In [180]:
book_sparse = csr_matrix(pt)

In [242]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [238]:
distance, suggestion = model.kneighbors(pt.iloc[237,:].values.reshape(1,-1), n_neighbors=6)

In [239]:
suggestion

array([[237, 240, 238, 241, 184, 291]], dtype=int64)

In [240]:
j = 0
for i in suggestion[0]:
    if j == 0:
        j+=1
        continue
    print(pt.index[i])

Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Sorcerer's Stone (Book 1)
Exclusive
Jacob Have I Loved